Repository HimanshuNarware/CareerZunction_Intern, pull requests merged in 2024-07, with the labels that each got.

#422 hover effect updated
  src/Component/Footer.css
  src/Component/Footer.jsx
Labels: gssoc, level2

#423 feat: Sending mail on contact submission
  package-lock.json
  package.json
  src/Component/Contact.jsx
Labels: gssoc, level3

#425 Added "Scroll Down Progress Bar" to The Website
  src/Component/ProgressBar.jsx
  src/index.css
  src/index.js
Labels: gssoc, level2

#436 Hide the Trail Effect in Mobile View
  public/index.html
Labels: gssoc, level1

#440 ✔️Implemented "Feedback Form" for CareerZunction!
  package-lock.json
  package.json
  src/App.js
  src/Component/Feedback.jsx
  src/Component/Feedbtn.jsx
  src/Style/feedback.css
  src/index.js
Labels: gssoc, level3

#439 Enhance the Footer Section and Added Extra Footer Links
  src/Component/Footer.css
  src/Component/Footer.jsx
Labels: gssoc, level2

#443 Enhanced the contact page
  src/Component/Contact.css
  src/Component/Contact.jsx
Labels: gssoc, level2

#444 Added Flipkart grid 6.0
  src/DB/DataBase.json
Labels: gssoc, level1

#441 Replaced with new twitter icon
  src/Component/Footer.jsx
Labels: gssoc, level1

#481 improve border in faqs
  src/Component/FAQ.css
Labels: gssoc, level2

#482 Added glassmorphism to cards in testimonials section
  src/Component/Documetation/blog.css
Labels: gssoc, level2

#466 Added the hover effects in footer
  src/Component/Contact.css
  src/Component/Contact.jsx
  src/Component/Documetation/Detail.css
  src/Component/Documetation/Detail.jsx
  src/Style/Home.css
Labels: gssoc, level2

#485 added jio internship
  src/DB/DataBase.json
Labels: gssoc, level1

#475 Added a dedicated "Terms and Conditions" Page
  src/App.js
  src/Component/Footer.jsx
  src/Component/Terms.jsx
Labels: gssoc, level2

#487 Walmart hackathon added
  src/DB/DataBase.json
Labels: gssoc, level1

#474 Added and Created Licensing Page Reflecting MIT License
  LICENSE
  package-lock.json
  src/App.js
  src/Component/Footer.jsx
  src/Component/Licensing.jsx
Labels: gssoc, level2

#473 Fixed sidebar in the mobile view
  src/Component/style.css
Labels: gssoc, level2

#491 Created "Contributors Page" Matched to Website Design Theme
  package-lock.json
  package.json
  src/Component/Contributors.css
  src/Component/Contributors.jsx
Labels: gssoc, level2

#493 fixed check now button in home page
  src/Style/Home.css
Labels: gssoc, level1

#469 added privacy policy page & made it responsive
  =2.1.4
  src/App.js
  src/Component/Footer.jsx
  src/Component/PrivacyPolicy.css
  src/Component/PrivacyPolicy.jsx
Labels: gssoc, level2

#483 improve ui of button
  src/Component/Documetation/Internship/internpage.css
Labels: gssoc, level2

#490 Designed Dedicated Page for Code of Conduct
  src/App.js
  src/Component/Codeofconduct.jsx
  src/Component/Footer.jsx
Labels: gssoc, level2

#492 improve hover in internship section
  src/Component/Documetation/Internship/internpage.css
Labels: gssoc, level2

#501 enhanced the pagination
  src/Component/pagination.css
Labels: gssoc, level2

#486 ✔️Improved UI of "FAQ Section" in the website
  src/Component/FAQ.jsx
Labels: gssoc, level2

#496 Feat/category wise internship filter
  src/Component/Documetation/Internship/InternPage.jsx
  src/Component/Documetation/Internship/filter.jsx
  src/Component/Documetation/Internship/internpage.css
  src/Component/pagination.jsx
Labels: gssoc, level3
