Repository HimanshuNarware/CareerZunction_Intern, pull requests merged in 2024-08, with the labels that each got.

#518 Created Privacy Policy Align with the Design of Other Legal Pages
  src/Component/Codeofconduct.jsx
  src/Component/Licensing.jsx
  src/Component/PrivacyPolicy.css
  src/Component/PrivacyPolicy.jsx
  src/Component/Terms.jsx
Labels: gssoc, level2

#517 Fixed FAQ Section Overalapping Footer Elements
  src/Component/FAQ.css
  src/Component/Footer.css
Labels: gssoc, level2

#514 Add filters filters for new buttons to filter out the internships on the basis of role and industry
  src/Component/Documetation/Internship/InternPage.jsx
  src/Component/Documetation/Internship/internpage.css
  src/DB/DataBase.json
Labels: gssoc, level3

#524 ✔️Added Diagonal Hovering Effect to Each Card!
  src/Component/Contributors.css
Labels: gssoc, level2

#527 added the testimonial section
  package-lock.json
  package.json
  src/Component/Home.jsx
  src/Component/Testimonials.css
  src/Component/Testimonials.jsx
Labels: gssoc, level3

#520 enhanced footer
  package-lock.json
  src/Component/Footer.css
  src/Component/Footer.jsx
Labels: gssoc, level2

#529 ✔️Added Dynamic "Last Updated" Functionality to All Legal Pages !
  src/Component/Licensing.jsx
  src/Component/PrivacyPolicy.jsx
  src/Component/Terms.jsx
Labels: gssoc, level2

#531 Added "About Us" Section for CareerZunction
  src/Component/Home.jsx
  src/Style/Home.css
  src/Style/util.css
  src/image/bg.gif
Labels: gssoc, level2

#528 fix #519 issue
  src/Component/Feedback.jsx
Labels: gssoc, level1

#535 Added Micorsoft Student Ambassadors and Infosys Internship
  src/DB/DataBase.json
Labels: gssoc, level2

#533 Fix #409 Add Subscribe to our NewsLetter feature
  package-lock.json
  package.json
  src/App.js
  src/Component/Newsletter.css
  src/Component/Newsletter.jsx
Labels: gssoc, level2

#545 ✔️Made Testimonials Responsive For All Screen-Sizes !
  src/Component/Testimonials.css
Labels: gssoc, level2

#549 Fix Social Icons
  src/Component/Contact.css
  src/Component/Contact.jsx
Labels: gssoc, level2

#550 Fixed the Contributors Data Fetching
  src/Component/Contributors.jsx
Labels: gssoc, level2

#497 Added dark/light mode toggle button in the website
  public/index.html
  src/Component/Licensing.jsx
  src/Component/Terms.jsx
Labels: gssoc, level3

#552 Added Icons to the Footer links
  package-lock.json
  src/Component/Footer.css
  src/Component/Footer.jsx
Labels: gssoc, level2

#551 Designed a new Logo for the Favicon of the Website
  public/favicon.png
  src/image/footer/favicon.png
Labels: gssoc, level2

#546 Updated Navbar
  src/Component/Navbar.jsx
  src/Component/style.css
Labels: gssoc, level2

#534 Add Newsletter Section to Footer
  src/Component/Footer.css
  src/Component/Footer.jsx
Labels: gssoc, level2
