Repository HimanshuNarware/CareerZunction_Intern, pull requests merged in 2024-06, with the labels that each got.

#249 [Styling]: Iconscolorchanged
  package-lock.json
  package.json
  src/Component/Documetation/Detail.css
  src/Component/Documetation/Detail.jsx
  src/Component/Footer.css
Labels: gssoc, level1

#291 Added Missing Images of Internships
  src/Component/Documetation/Internship/InternPage.jsx
  src/Component/Documetation/Internship/internpage.css
  src/DB/DataBase.json
Labels: gssoc

#239 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level2
